---
- hosts: all
  vars:
    workspace: "{{ lookup('env','WORKSPACE') }}"
    target: "{{ lookup('ini', 'artifact_target section=common file={{ workspace }}/description.ini') }}"
    jvm_opts: "{{ lookup('ini', 'jvm_opts section=test file={{ workspace }}/description.ini') }}"
    java_opts: "{{ lookup('ini', 'java_opts section=test file={{ workspace }}/description.ini') }}"
    app_opts: "{{ lookup('ini', 'app_opts section=test file={{ workspace }}/description.ini') }}"
  tasks:
    - name: shutdown app
      command: "{{ app_home }}/shutdown.sh -force"
      ignore_errors: yes
    - name: deploy new packages
      copy:
        src: "{{ workspace }}/{{ target }}"
        dest: "{{ app_home }}/webapps/"
    - name: render app_opts
      template:
        src: "app_opts.sh.j2"
        dest: "{{ app_home }}/app_opts.sh"
    - name: start app
      command: "nohup {{ app_home }}/startup.sh"
    - debug:
        msg: "{{ app_home }}, {{ target }}"
